name: Cypress test Ci/CD
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      -  name: Checkout
         uses: actions/checkout@v3.6.0
      -  name: Cypress.io
         uses: cypress-io/github-action@v5.8.2
        
          
