name: Cypress test Ci/CD
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      -  name: Checkout
         uses: actions/checkout@v3.6.0

      - name: Setup Node.js environment
        uses: actions/setup-node@v4.0.0

      - name: Install ALL Dependencies
        run: |
            npm install
            npm list
         
      -  name: Cypress E2E Tests
         uses: cypress-io/github-action@v5.8.2
         with:
           runTests: false 
          
